export const INSTALL_ERROR_CODES = {
  BROWSER_UNSUPPORTED: 'INSTALL_BROWSER_UNSUPPORTED',
  INSECURE_CONTEXT: 'INSTALL_INSECURE_CONTEXT',
  OPFS_UNAVAILABLE: 'INSTALL_OPFS_UNAVAILABLE',
  WORKER_UNAVAILABLE: 'INSTALL_WORKER_UNAVAILABLE',
  STORAGE_QUOTA_INSUFFICIENT: 'INSTALL_STORAGE_QUOTA_INSUFFICIENT',
  NETWORK_ERROR: 'INSTALL_NETWORK_ERROR',
  INTEGRITY_MISMATCH: 'INSTALL_INTEGRITY_MISMATCH',
  CANCELLED: 'INSTALL_CANCELLED',
  CLEAR_FAILED: 'INSTALL_CLEAR_FAILED',
};

export const RUNTIME_ERROR_CODES = {
  MODEL_NOT_INSTALLED: 'MODEL_NOT_INSTALLED',
  INIT_FAILED: 'RUNTIME_INIT_FAILED',
  MODEL_LOAD_FAILED: 'MODEL_LOAD_FAILED',
};

export function createLlmError(code, message = code, extra = {}) {
  const error = new Error(message);
  error.code = code;
  Object.assign(error, extra);
  return error;
}
