export const INSTALL_ERROR_CODES = {
  BROWSER_UNSUPPORTED: 'INSTALL_BROWSER_UNSUPPORTED',
  INSECURE_CONTEXT: 'INSTALL_INSECURE_CONTEXT',
  CONTROL_REQUIRED: 'INSTALL_CONTROL_REQUIRED',
  NETWORK_ERROR: 'INSTALL_NETWORK_ERROR',
  ASSET_MISSING: 'INSTALL_ASSET_MISSING',
  INTEGRITY_MISMATCH: 'INSTALL_INTEGRITY_MISMATCH',
  CLEAR_FAILED: 'INSTALL_CLEAR_FAILED',
};

export const RUNTIME_ERROR_CODES = {
  MODEL_NOT_INSTALLED: 'MODEL_NOT_INSTALLED',
  INIT_FAILED: 'RUNTIME_INIT_FAILED',
};

export function createLlmError(code, message = code, extra = {}) {
  const error = new Error(message);
  error.code = code;
  Object.assign(error, extra);
  return error;
}
